services:

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"

  chatbot:
    container_name: chatbot
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app